Hanami::Model.migration do
  change do
    create_table :urls do
      primary_key :id

      column :href, String, null: false

      # generated by Hanami
      column :created_at, DateTime, null: false
      column :updated_at, DateTime, null: false

      # if we want to have users in our app, we need to
      # scope uniqueness by [href, user_id]
      index :href, unique: true
    end
  end
end
