language: ruby
rvm: 2.6.6
cache:
  bundler: true
  directories:
  - "/home/travis/.rvm/"
services:
- postgresql
before_install:
- gem install bundler
script:
- HANAMI_ENV=test bundle exec hanami db create
- HANAMI_ENV=test bundle exec hanami db migrate
- bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: WwwV/+TPuQqqOMobzwxSA/DUP/tz6RHnJZ1E1ZntIrCstUbcrrxc0Fd7mw5A8f84ka1y/KdFlGRfmSnPpWF5ZFPNQg9DAXtJ84sPxNtHDpawWVk0YZeoh5QbMNeZtkgClXIcjFjqzqM6+E3OGf60JF7qZ2lSKLld+vjkAC60EkU/4IE1CnPufMWGDeJWpSyNrwX/tcV+T9maPjR2xFBdWGgD1jgbYkc6PJRkpHcI1vatdLEDBw9BHdqP0hhcoWB3RYXqqutRGLQDn1fRgYJ7zR96YxeT+3/9/wet+RYPUYCDEZHqbymbUBHfl2rfMHuDg3i+OT0tKN8r87e+cZLROU5NfoD57ComR/jwIM5Uq22via7vyWFA2k68LvCgWkkqPx6aZLTAodaztA+eUR4FNv8M48cB5u4HoQp6ZvbTTruzWNllSHmHCmgys+Q7/Lajh3+G/rWTT25ItmJ22g78DdbwTbVDpfxCD/PSfMIMAlQk5JIFO/BGI7GfSooHdNXvZUlra5hPaXVhngjfJrWnMn1dCJAHwNYOLaPf8qdfRhGPjgy2oBFDgOR3nrAOc9RmliQrVSLiSWfBwQCNty5C92TbtPv1uQxu0ZJUK1t1pZm+4Bur9w1Ecy2RuwWGdVmziLNUQ2BWm/gkIgSwkrktK22dWTkIJTssyJtoT6wKTTw=
  app: hanami-linkin
