language: ruby
rvm: 2.5.3
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
services:
  - postgresql
script:
  - HANAMI_ENV=test bundle exec hanami db create
  - HANAMI_ENV=test bundle exec hanami db migrate
  - bundle exec rake test