version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: linkin_development
    ports:
      - 5432:5432

  web:
    build:
      context: .
      args:
        environment: development
    env_file:
      - .env.development
    command: hanami server
    volumes:
      - .:/app
    ports:
      - 4555:2300
    depends_on:
      - db
    links:
      - db
