version: '3.1'
services:
  app:
    build:
      context: .
      args:
        environment: development
    command: bash -c "rails db migrate && rails server"
    volumes:
      - .:/app
    ports:
      - 3000:3000
