version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: linkin_development

  web:
    build:
      context: .
      args:
        environment: development
    command: hanami server
    ports:
      - 4555:2300
    depends_on:
      - db
    links:
      - db
